name = "DynamicMixtures"
uuid = "a45eadbe-4e20-4c8c-a051-cdc822344751"
authors = ["Victhor Sartório <vct.sartor@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
