name = "DynamicMixtures"
uuid = "a45eadbe-4e20-4c8c-a051-cdc822344751"
authors = ["Victhor Sartório <vct.sartor@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicLinearModels = "dc5eaf77-5719-4a86-9393-27bd7a74eb3e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DynamicLinearModels = "^0.3.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
